server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://192.168.1.97:3308/jg?characterEncoding=UTF-8
    username: loanadmin
    password: loanadmin
    driver-class-name: com.mysql.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create
logging:
  level:
    org.springframework.security: DEBUG