#eureka:
#  instance:
#    statusPageUrlPath: /info
#    healthCheckUrlPath: /health
#    prefer-ip-address: true
#  client:
#    serviceUrl:
#      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/